### ISSUE TITLE
[教程大纲] Jenkins 统一身份认证之 OIDC

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-zh/jenkins-zh#416]
### OIDC

[dex](https://github.com/dexidp/dex) 是 OpenID Connect Identity (OIDC)

启动 [dex](https://github.com/dexidp/dex)
```
local=192.168.31.140
mkdir -p example
cat <<EOF > example/config.yaml
issuer: http://${local}:5556/dex
storage:
  type: sqlite3
  config:
    file: ':memory:'
web:
  http: 0.0.0.0:5556
telemetry:
  http: 0.0.0.0:5558
staticClients:
- id: example-app
  redirectURIs:
  - 'http://${local}:8080/securityRealm/finishLogin'
  - 'http://127.0.0.1:5555/callback'
  - 'http://${local}:8080/jenkins/securityRealm/finishLogin'
  name: 'Example App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0
connectors:
- type: mockCallback
  id: mock
  name: Example
enablePasswordDB: true
staticPasswords:
- email: "admin@example.com"
      # bcrypt hash of the string "password"
  hash: '\$2a\$10\$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W'
  username: "suren"
  group: admin
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
EOF
docker run -p 5556:5556 -p 5558:5558 -v $(pwd)/example:/example dexidp/dex serve /example/config.yaml
```

你需要把 变量`local` 的值 `192.168.31.140` 修改为你的实际地址。

启动 Jenkins 并安装 [oic auth 插件](https://github.com/jenkinsci/oic-auth-plugin)，或者，直接使用下面的[配方](https://github.com/jenkins-zh/jenkins-formulas/blob/master/formulas/oic-auth.yaml)。（修改 Jenkins 的根服务地址）
```
jcli center start --setup-wizard=false --image jenkinszh/jenkins-oic-auth --version 2.249.1 -m docker --c-user root
```

配置  [oic auth 插件](https://github.com/jenkinsci/oic-auth-plugin)
```
user name field name: name
email field name: email
```
