### ISSUE TITLE
[教程大纲] Jenkins & OpenTelemetry

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-zh/jenkins-zh#428]
### 标题一
```
hd get -t 8 https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/download/v0.21.0/otelcontribcol_linux_amd64
mv otelcontribcol_linux_amd64 otelcontribcol_linux
chmod u+x otelcontribcol_linux
```

### 标题一
```
receivers:
  otlp:
    protocols:
      grpc:
  zipkin:

exporters:
  jaeger_thrift:
    url: "http://localhost:16686/api/traces"
  logging:
  zipkin:
    endpoint: "http://localhost:9411/api/v2/spans"

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp, zipkin]
      exporters: [zipkin, jaeger_thrift, logging]
      processors: [batch]
```

`./otelcontribcol --config config.yaml`

### 参考资料
https://github.com/open-telemetry/opentelemetry-collector-contrib
http://github.com/jaegertracing/jaeger

/kind tutorial
